feat: adding initial testing for localstack s3 usage
snyk/vervet pull request #175
Opened 2022-04-08 19:50 UTC by genslein

Still getting the testcontainers testing working

2022-04-08 20:05 UTC, cmars reviewed
Just some idle thoughts, this seems early stage. Do we want to continue with the AWS-specific storage? I thought WAL-G might replace it.

2022-04-08 20:05 UTC, cmars commented on vervet-underground/internal/storage/s3/aws_s3_client_test.go
> +	}
I'd never assume a particular port is available in a `go test` test. Or that I have permissions to access a Docker socket. Maybe I want to use podman? Or CI connects to a remote Docker instance?

For an integration test like this, I'd orchestrate the whole thing with docker-compose, and then configure ports, URLs and such completely via env vars when running the test itself in a container. Kind of like how the sample service CI works w/envoy &tc.

With a repeatable isolated environment like that, these integration tests could be unit tests that t.Skip() unless a "this is a CI test" env var is set. That way you can `go test` some things without a heavy setup.

2022-04-08 20:10 UTC, genslein commented on vervet-underground/internal/storage/s3/aws_s3_client_test.go
> +	}
See my draft comment in the top

2022-04-12 16:03 UTC, genslein commented
the `wal-g` storages repo was sunset and internalized to wal-g. WALG only exports the full executable, not the library so can't reuse it. Could ask if they would re-export it.

2022-04-12 16:04 UTC, genslein commented on vervet-underground/internal/storage/s3/aws_s3_client.go
> +	"github.com/aws/aws-sdk-go-v2/credentials"
see https://github.com/snyk/vervet/pull/176

2022-04-12 17:14 UTC, genslein commented
@cmars its failing on test containers go for snyk. Got magic to exclude test dependencies?

2022-04-13 15:24 UTC, davidharrigan commented on vervet-underground/internal/storage/s3/client.go
> +		panic(err)
should we be returning an error here instead?

2022-04-13 20:17 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +		panic(err)
Yup changed to return err

2022-04-18 15:05 UTC, davidharrigan reviewed
overall, looks great. I'll come back and take another look at `CollateVersions` based on our discussions earlier.

2022-04-18 15:05 UTC, davidharrigan commented on vervet-underground/internal/storage/s3/client.go
> +	if smith := handleAwsError(err); smith != nil {
ah maybe because `github.com/aws/smithy-go`?

2022-04-18 16:29 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +	if smith := handleAwsError(err); smith != nil {
Exactly, smithy-go is a special flavor of errors

2022-04-18 16:30 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +	_, putErr := s.PutObject(key, reader)
Linter errors for shadowing vars. If there's a way around it, happy to revert

2022-04-18 17:35 UTC, genslein commented on vervet-underground/internal/storage/s3/client_test.go
> +	}
Until we enable the localstack tests in CI, not really sure there is

2022-04-18 17:55 UTC, davidharrigan commented on vervet-underground/internal/storage/s3/client.go
> +	_, putErr := s.PutObject(key, reader)
hmm I don't see anything being shadowed here, I wonder this looked differently before?

2022-04-18 18:01 UTC, davidharrigan commented on vervet-underground/internal/storage/s3/client.go
> +		blob, readerErr := io.ReadAll(rev.Body)
do we need to close the body here?  Maybe lines 194-here can be extracted as a function so we can `defer` body close.

2022-04-18 23:36 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +	_, putErr := s.PutObject(key, reader)
using `_, err := s.PutObject` or  `_, err = s.PutObject` it screamed very loudly I made the above change.

2022-04-18 23:43 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +		blob, readerErr := io.ReadAll(rev.Body)
Add an immediate closer after reading for fast fail

2022-04-19 13:09 UTC, davidharrigan approved these changes
couple more small comments, but looks great! 🚀

2022-04-19 13:09 UTC, davidharrigan commented on vervet-underground/internal/storage/s3/client_test.go
> +	//c.Assert(err, qt.IsNil)
maybe mark this as todo with a short description? I'm guessing we want to resurrect this when we can use test container here?

2022-04-19 14:56 UTC, genslein commented
This is now usable in `docker-compose up -d`

I just missed demo time so next one 😭 

add a `config.json` file with the following config locally:

```json
{
  "services":
  [
    "https://api.dev.snyk.io/v3"
  ],
  "host": "0.0.0.0",
  "storage": {
    "type": "s3",
    "region": "us-east-1",
    "endpoint": "http://localstack:4566",
    "accessKey": "test",
    "secretkey": "test",
    "sessionkey":"test"
  }
}
```

2022-04-19 15:51 UTC, cmars requested changes
Some comments below.

Recommended changes on docs are just nits.

Things I'd like addressed:

- Errors should be propagated and returned rather than panicked on.
- Naming of error variables. Not using `err` tends to be... error prone, and harder to read. If a linter rule is getting in the way and not letting you reuse `err`, I'm seriously wondering if it is not a good rule and should be removed from our golangci-lint config. Open to discussion here, but I'm really going to need to understand the reason behind it...

2022-04-19 15:51 UTC, cmars commented on vervet-underground/Makefile
> +.PHONY: run fmt lint tidy test test-coverage clean test-localstack
If we place a PHONY next to each target (which I tend to prefer, as it's harder to keep a single line like this up to date over time) then we could/should remove this line.

2022-04-19 15:51 UTC, cmars commented on vervet-underground/config/config.go
> +	Storage  map[string]string `json:"storage"`
Could this be more strongly-typed than a free-form string map? Perhaps a

```
type StorageConfig struct {
  Type string `json:"type"`
}
```

?

2022-04-19 15:51 UTC, cmars commented on vervet-underground/internal/scraper/s3_scraper_test.go
> +		return
```suggestion
		c.Skip("CI not enabled")
```

https://pkg.go.dev/testing#T.Skip doesn't need the early return -- it will end the test for you.

2022-04-19 15:51 UTC, cmars commented on vervet-underground/internal/storage/s3/README.md
> +`localstack config validate` to verify docker-compose setup
```suggestion
  * `localstack config validate` to verify docker-compose setup
```

2022-04-19 15:51 UTC, cmars commented on vervet-underground/internal/storage/s3/README.md
> +* `localhost:4566/health` will show status of all mimicked services
```suggestion
* To validate in Docker-compose `docker-compose up -d`
  * `localhost:4566/health` will show status of all mimicked services
```

2022-04-19 15:51 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +	BucketName             = "vervet-underground-specs"
Is this something we might want to make configurable? Perhaps this should be defaultBucketName.

Do these consts need to be exported outside this package?

2022-04-19 15:51 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +type StaticKeyCredentials struct {
Please godoc exported symbols. Or, perhaps we don't need to export them outside `s3`?

2022-04-19 15:51 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +func New(awsCfg *Config) *Storage {
Can this return the `Storage` interface, hiding the s3 impl completely?

2022-04-19 15:51 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +	}
`New` should return a (Storage, error) and propagate the error rather than panic.

2022-04-19 15:51 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +		log.Fatal().Err(err).Msg("Cannot load the AWS configs")
Error should be returned, possibly with annotation. Even if that results in a process exit nonzero, we should handle that at the top in service initialization.

2022-04-19 15:54 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +	//collatedVersionedSpecs storage.CollatedVersionMappedSpecs
Sure

2022-04-19 16:11 UTC, genslein commented on vervet-underground/config/config.go
> +	Storage  map[string]string `json:"storage"`
Each config for S3 and GCS has slightly different config requirements. That means additional JsonParsing in each Storage Client. I'd rather save that hardening for after this PR and #184.

2022-04-19 16:59 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +	BucketName             = "vervet-underground-specs"
I could move them to top-level storage. Ideally, users wouldn’t have to guess to create a bucket and folder structure to use here

2022-04-19 17:12 UTC, cmars reviewed
A few minor things need fixing, on closer review, but I think we're getting close!
* Some places look like a nil deref is possible on errors
* Test cleanup concerns

2022-04-19 17:12 UTC, cmars commented on vervet-underground/internal/storage/storage.go
> +			log.Warn().Err(err).Msgf("service.base url misconfigured. Falling back %v", name)
If err != nil, I think we may end up with a nil deref below. parsedUrl would be nil...

2022-04-19 17:12 UTC, cmars commented on vervet-underground/server.go
> +		panic("unable to initialize storage client")
Consider using https://pkg.go.dev/github.com/rs/zerolog?utm_source=godoc#Logger.Fatal ? Though, a panic will definitely tell you where it happened...

2022-04-19 17:12 UTC, cmars commented on vervet-underground/server.go
> +		if err != nil {
nit:
```suggestion
		if err := encoder.Encode(map[string]interface{}{"msg": "success", "services": services}); err != nil {
```

2022-04-19 18:56 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +	_, putErr := s.PutObject(key, reader)
resolved, removed bugged ci rule

2022-04-19 20:08 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +type StaticKeyCredentials struct {
Done

2022-04-19 20:46 UTC, cmars approved these changes
More minor questions & comments below, but nothing blocking, this is generally looking good!

2022-04-19 20:46 UTC, cmars commented on vervet-underground/internal/scraper/scraper.go
> +		if u.Hostname() == "localhost" || u.Hostname() == "127.0.0.1" {
Why is this special case necessary?

2022-04-19 20:46 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +		err = multierr.Append(err, rev.Body.Close())
Interesting. Usually I'd fail on the read error, but `defer rev.Body.Close()` and not fail on that error. If we're successful in reading the entire stream, but fail to close it, did we fail in our objective here? This might be a really remote-to-impossible situation, but it's a subtle difference in behavior...

2022-04-19 20:46 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +	log.Printf("S3 PutObject response: %+v", r)
Should this be logged at debug level?

2022-04-19 20:46 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +		if smith = handleAwsError(err); smith != nil {
Mr. Anderson? Oh, ok, I see David's question answered below :D

2022-04-19 20:46 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +	log.Printf("S3 DeleteObject response: %+v", r)
Debug level?

2022-04-19 20:46 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +	log.Printf("S3 ListObject response: %+v", r)
Debug?

2022-04-19 20:46 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +		return "", "", ""
This seems like an error condition. Generally I'd recommend returning it. Kind of like how https://pkg.go.dev/net#SplitHostPort does in the stdlib. Being internal & not exported, I'll leave it up to you, my only real ask is that you handle & test this case.

2022-04-19 20:46 UTC, cmars commented on vervet-underground/internal/storage/s3/client.go
> +	var ae smithy.APIError
nit:

```suggestion
	var opErr *smithy.OperationError
	var apiErr smithy.APIError
```

2022-04-19 20:53 UTC, genslein commented on vervet-underground/internal/scraper/scraper.go
> +		if u.Hostname() == "localhost" || u.Hostname() == "127.0.0.1" {
For tests or local, port is unique in identifying different services. Since both accept traffic, both are valid config

2022-04-19 20:54 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +		err = multierr.Append(err, rev.Body.Close())
I suppose, I worry about leaking the connection tho if h

2022-04-19 20:55 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +	log.Printf("S3 PutObject response: %+v", r)
Yes I missed that

2022-04-19 20:55 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +		if smith = handleAwsError(err); smith != nil {
Lol

2022-04-20 12:59 UTC, genslein commented on vervet-underground/internal/storage/s3/client.go
> +		return "", "", ""
done

2022-04-20 13:06 UTC, merged