fix: add context propagation to VU
snyk/vervet pull request #200
Opened 2022-05-05 22:40 UTC by genslein

https://github.com/snyk/vervet/issues/198

Fixes some stylings from #197 as well

2022-05-05 23:21 UTC, cmars requested changes
Recommend that we do not store the context in a struct. For more background on why, I can also recommend https://go.dev/blog/context-and-structs.

One reason to violate this general rule is for backwards compatibility, like http/Request.Context. Here we shouldn't be bound by compatibility though, as these are internal packages. Best to make a clean break IMO.

2022-05-05 23:21 UTC, cmars commented on vervet-underground/internal/storage/gcs/client.go
> +	ctx              context.Context
Context should almost never be stored in a struct. It should be passed to every function or method that propagates it, as the first argument. This means we'll need to change the Storage interface and all its implementations. Some like mem can ignore the context. I think it should be fine to do so, since these are internal packages.

> Programs that use Contexts should follow these rules to keep interfaces consistent across packages and enable static analysis tools to check context propagation:
>
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx: 

(Source: https://pkg.go.dev/context#pkg-overview)

2022-05-05 23:21 UTC, cmars commented on vervet-underground/internal/storage/gcs/client.go
> +	ctx, cancel := context.WithTimeout(s.ctx, time.Second*50)
Generally it's best to just pass the context through and let the caller decide how long they're willing to wait (or cancel the context with a signal handler, etc).

2022-05-06 15:40 UTC, genslein commented on vervet-underground/internal/storage/gcs/client.go
> +	ctx, cancel := context.WithTimeout(s.ctx, time.Second*50)
Refactor makes this obsolete; removed

2022-05-06 15:41 UTC, genslein commented on vervet-underground/internal/storage/gcs/client.go
> +	ctx              context.Context
Argh, my lack of go-ism...I've done the refactor here

2022-05-06 16:28 UTC, cmars approved these changes
Looks good now, thanks!

2022-05-06 17:00 UTC, jcsackett approved these changes
Looks good, thanks!

2022-05-06 19:10 UTC, merged