Test/duplicate spec files
snyk/vervet pull request #240
Opened 2022-09-05 11:37 UTC by juliabanerjee

2022-09-05 11:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/snyk/vervet?pullRequest=240) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/snyk/vervet?pullRequest=240) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/snyk/vervet?pullRequest=240) it.</sub>

2022-09-05 11:46 UTC, gablaxian commented on resource.go
> +	specYmls, err := filepath.Glob(epPath + "/*/spec.yml")
I took a quick look into `Glob` and I'm wondering now that, as I heard the pattern `spec.{yaml, yml}` doesn't work, does this instead:
`spec.ya?ml`? We may still be able to simplify the logic.

2022-09-05 12:52 UTC, juliabanerjee commented on resource.go
> +	specYmls, err := filepath.Glob(epPath + "/*/spec.yml")
I tried that before but it didn't work because the function is looking for a match to the specific string given. Therefore, it would be looking for a file matching the name "spec.ya?ml" rather than a spec.yaml and/or a spec.yml

2022-09-06 12:55 UTC, cmars commented on resource.go
> +	specYmls, err := filepath.Glob(epPath + "/*/spec.yml")
Suggest the use of github.com/bmatcuk/doublestar for globbing here, which [supports patterns](https://github.com/bmatcuk/doublestar#patterns) like `{yaml,yml}`. doublestar is already a vervet dependency.

2022-09-06 16:09 UTC, juliabanerjee commented on resource.go
> +	specYmls, err := filepath.Glob(epPath + "/*/spec.yml")
Thank you, I will give that a go

2022-09-07 13:18 UTC, gablaxian approved these changes

2022-09-07 13:39 UTC, cmars requested changes

2022-09-07 13:39 UTC, cmars commented on resource_test.go
> +	c.Assert(err, qt.IsNil)
I think this should result in an error, if there are duplicate specs in the same directory.

2022-09-07 13:39 UTC, cmars commented on resource.go
> +	// It is assumed that duplicate specs would cause an error elsewhere in vervet
I disagree with this assumption. I think we should detect and error on duplicates (`spec.yaml` and `spec.yml`) here, rather than place the burden of de-duplicating on the caller.

2022-09-08 16:47 UTC, cmars approved these changes
Looks good now, thanks for this!

2022-09-09 13:19 UTC, merged