feat: service collation algorithm
snyk/vervet pull request #94
Opened 2021-12-09 21:25 UTC by genslein

Implements both in-memory storage algorithm
and aggregate service spec merges to the
collated Vervet Underground Spec per
version identified.

Scraper test added for post-processing collation on scraping.

2021-12-10 15:08 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +type MemoryStorage struct {
Go names should avoid repetition. Becuase the package is `mem`, `Storage` is unambiguous.

You'll see this pattern repeated throughout the Go standard library. `bufio.Reader`, `crypto/rand.Reader`, `io.Reader`. Consider `http.Header` vs something like `http.HTTPHeader`; you don't need to call it `HTTPHeader` because you always refer to it in its package.

This differs from other languages like Java, Typescript or Rust where you often import symbols directly out of packages into the current context. Pulling symbols into the current context from another package is possible in Go (`import . "somepackage"`) but it's highly irregular to do so and strongly discouraged.

Not only does this improve clarity, it tends to force package names to be meaningful.

2021-12-10 15:10 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +type VersionedResourceMap map[string]vervet.VersionSlice
Do these types need to be exported outside of `mem`? If not, they shouldn't be. In general, it's good to keep the API surface small where possible.

2021-12-10 15:15 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +	typedDigest := Digest(digest)
Hmm... makes me think the `Digest` type should be pulled up into the `storage` package, and used there in `storage.Digest(contents []byte) Digest`?

2021-12-10 15:19 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +			vervet.Merge(dst, src, true)
#93 might fix panics you've seen here? If not, let's dig into why, could be a bug in merge where we've missed something and hit an uninitialized map. (A drive-by fix there would be great! 🙏)

2021-12-10 15:27 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +	typedDigest := Digest(digest)
very reasonably

2021-12-10 15:28 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +			vervet.Merge(dst, src, true)
I  believed this was me trying to use a nil pointer for `dst` I'll remove this.

2021-12-10 15:33 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +	typedDigest := Digest(digest)
I need to change the name of the function to not conflict with the type name

2021-12-10 15:42 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +type VersionedResourceMap map[string]vervet.VersionSlice
I can re-expose later, fine to lower case for now as I build

2021-12-10 16:00 UTC, cmars reviewed
Round two.

2021-12-10 16:00 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *MemoryStorage) CollateVersions() error {
Please add a godoc comment that explains how this is intended to be used, rather than a description of its implementation. That might involve some explanation of what it does, but only in the context of what I need to know in order to use it.

2021-12-10 16:00 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *MemoryStorage) CollateVersions() error {
I _think_ what this does is prepare the state of the storage such that I might be able to ask it questions after calling it, from a point-in-time view of all the versions of all the service APIs. And those questions are methods we haven't added yet? Does this sound right?

2021-12-10 16:00 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *MemoryStorage) GetCollatedVersionSpecs() CollatedVersionMappedSpecs {
```suggestion
func (s *MemoryStorage) Versions() CollatedVersionMappedSpecs {
```

It may be fair to assume that the versions our storage provides are always collated, if that is its job to do that for us. So perhaps the name can be more concise?

2021-12-10 16:00 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +type CollatedVersionMappedSpecs map[vervet.Version]openapi3.T
Maybe this can be expressed with a more concise name? It seems like it's a "collection of OpenAPI spec versions indexed by version". Maybe `SpecVersions`?

2021-12-10 16:00 UTC, cmars commented on vervet-underground/internal/scraper/scraper_test.go
> +	c.Assert(len(collated), qt.Equals, 4)
It'd be good to assert that the collated versions have the expected contents -- did we collate correctly?

Perhaps this can be spot-checked here, but we'll likely want fixture-based tests with real OpenAPI files for this.

2021-12-10 16:42 UTC, cmars requested changes
Implementation-wise this looks very good. Only major concern that needs fixing is the deep-copy when returning the collated specs-by-version.

You might have noticed I'm particular about naming, it's an obsession. Generally I prefer the most concise name that still clearly conveys intent and meaning. Nouns rather than verbs for getters, plural form instead of "-Collection", "-List", etc.

2021-12-10 16:42 UTC, cmars commented on vervet-underground/internal/storage/digest.go
> +type Digest string
Please add a godoc comment.

2021-12-10 16:42 UTC, cmars commented on vervet-underground/internal/storage/digest.go
> +func GenerateDigest(contents []byte) Digest {
This is getting more into bikeshed territory, but I wonder if this is really a constructor? I can go either way on this.

```suggestion
// NewDigest returns the digest of the given contents.
func NewDigest(contents []byte) Digest {
```

2021-12-10 16:42 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> -	// TODO: implement notify versions; update sunset when versions are removed
Note that this is also the only way you know a sunset version was removed...

2021-12-10 16:42 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *Storage) GetCollatedVersionSpecs() collatedVersionMappedSpecs {
You'll need to return a completely distinct copy of this map's contents here (deep, not shallow); you're returning a reference to data that is protected by a mutex elsewhere.

The returned type should be exported. I think a shorter name that describes what the type is (a map of specs keyed by version) rather than how it was made (collated and mapped) would be better.

2021-12-10 16:42 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +	if !ok {
We just added this key at [line 117](https://github.com/snyk/vervet/pull/94/files#diff-90da75d2382757cdf44cc3ac56158069e0741cba584ef5347c6afd81624dc558R117) above if it did not exist -- so I don't think this is possible.

Am I missing something?

2021-12-10 16:42 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +	contentRevisionCollection := make([]ContentRevision, 0)
```suggestion
	contentRevisions := make([]ContentRevision, 0)
```

2021-12-10 16:42 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *Storage) gatherVersionsRequiredToCollate() {
```suggestion
func (s *Storage) updateCollatedVersions() {
```

2021-12-10 16:42 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +	s.collatedVersionedSpecs[version] = *dst
If you're doing something trivial with a mutex held, and there's no risk of early return or panic, you can:

```suggestion
	s.mu.Lock()
	s.collatedVersionedSpecs[version] = *dst
	s.mu.Unlock()
```

2021-12-10 20:08 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +type CollatedVersionMappedSpecs map[vervet.Version]openapi3.T
The naming with reuse of `SpecVersions`, `Version`, and `Doc` makes me concerned about shortening the name here. It's not well understood these are post-Merge ContentRevision Service Specs.

I'm also intentionally strong-typing here to make it obvious not to just put anything in for the keys themselves. 

Happy to talk through a better naming strategy but for the layperson, I'm pretty sure shortening the name will make this a lot less obvious what's happening

2021-12-10 20:13 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> -	// TODO: implement notify versions; update sunset when versions are removed
Sunset isn't implemented anywhere. I'd like to separate that out of scope

2021-12-10 20:17 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> -	// TODO: implement notify versions; update sunset when versions are removed
I agree it is out of scope, but it is absolutely a TODO to follow up on, please keep the comment. A sunset in a service must propagate to the aggregated SaaS view.

2021-12-10 20:20 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +type CollatedVersionMappedSpecs map[vervet.Version]openapi3.T
We can always sort out names later, it is an internal API after all. No worries, just suggestions.

2021-12-10 20:25 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *Storage) GetCollatedVersionSpecs() collatedVersionMappedSpecs {
To be clear, with this issue addressed, I think it's landable. This is the only thing really blocking IMO.

2021-12-10 20:26 UTC, genslein commented on vervet-underground/internal/scraper/scraper_test.go
> +	c.Assert(len(collated), qt.Equals, 4)
Yeah, I think this will have to come from fixtures to validate this from real specs. This was a stopgap to validate the algorithm. I think next is doing the fixtures and integrating with the static service list to target in a subsequent PR

2021-12-10 20:28 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *MemoryStorage) GetCollatedVersionSpecs() CollatedVersionMappedSpecs {
`Versions` would returning the `collatedVersions vervet.VersionSlice` value. These are the actual OAS.

Like `/openapi` vs. `/openapi/{version}`. It's the latter,  but for each one. I used it as testing function to validate my assumptions. It can be removed and is probably not permanent.

2021-12-10 20:28 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *MemoryStorage) GetCollatedVersionSpecs() CollatedVersionMappedSpecs {
Again, where naming too short is failing here.

2021-12-10 20:34 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *MemoryStorage) CollateVersions() error {
Yes-ish? This is basically the background processing of all service specs once they are in our memory storage.

This scraping operates in phases.

* Get all versions for all services. Reconcile digest differences for each service's versions if there are non-breaking updates.
* (Where `CollateVersions` comes in) Review all memory records of services to determine a list of unique vervet.Versions. 
  * Use that list to generate VU's collated spec for each version identified. 
  * For each version, search our memory storage to determine if each service has a fuzzy match on the VU version being compiled, and if so, add the latest digest fo compilation
  * Compile each version's ContentRevisions gathered via the search and save to memory

2021-12-10 20:35 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +func (s *MemoryStorage) CollateVersions() error {
🚨 🚨  Bear in mind since this is memory, and not persistent, restarts (deployments/syncs) and containers crashes lose digests.

2021-12-10 20:59 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +	if !ok {
removed, I think a leftover from testing

2021-12-10 22:36 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> -	// TODO: implement notify versions; update sunset when versions are removed
Added the TODO back in 👍

2021-12-10 22:43 UTC, genslein commented
There seems to be a race/flakiness to the Collate test I added, I'm not really sure where it's coming from but I see  the following `github.com/snyk/vervet.mergePaths` was what was giving me trouble before, like there's a race condition setting docs up:

```bash
{"level":"error","error":"no matching version","time":"2021-12-10T17:40:32-05:00","message":"Could not resolve for service http://127.0.0.1:50101 version 2021-09-01"}
{"level":"error","error":"no matching version","time":"2021-12-10T17:40:32-05:00","message":"Could not resolve for service http://127.0.0.1:50101 version 2021-09-16"}
--- FAIL: TestScraperCollation (0.00s)
panic: assignment to entry in nil map [recovered]
        panic: assignment to entry in nil map

goroutine 16 [running]:
testing.tRunner.func1.2({0x1434a80, 0x152c190})
        /usr/local/opt/go/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /usr/local/opt/go/libexec/src/testing/testing.go:1212 +0x218
panic({0x1434a80, 0x152c190})
        /usr/local/opt/go/libexec/src/runtime/panic.go:1038 +0x215
github.com/snyk/vervet.mergePaths(0xc000400c30, 0xc000400d00, 0x1)
        /Users/gabrielenslein/go/pkg/mod/github.com/snyk/vervet@v1.2.1/merge.go:135 +0xf2
github.com/snyk/vervet.Merge(0xc000400c30, 0xc000400d00, 0x1)
        /Users/gabrielenslein/go/pkg/mod/github.com/snyk/vervet@v1.2.1/merge.go:20 +0x7f
vervet-underground/internal/storage/mem.(*Storage).mergeContentRevisions(0xc0000a0d70, {{0x14b2265, 0xc00007dab0, 0x0}, 0x0}, {0xc000402e60, 0x2, 0xc0003206e0})
        /Users/gabrielenslein/go/src/github.com/snyk/vervet/vervet-underground/internal/storage/mem/mem.go:265 +0x235
vervet-underground/internal/storage/mem.(*Storage).collateVersion(0xc0000a0d70, {{0x0, 0xed8d48000, 0x0}, 0x4})
        /Users/gabrielenslein/go/src/github.com/snyk/vervet/vervet-underground/internal/storage/mem/mem.go:235 +0x646
vervet-underground/internal/storage/mem.(*Storage).CollateVersions(0xc0000a0d70)
        /Users/gabrielenslein/go/src/github.com/snyk/vervet/vervet-underground/internal/storage/mem/mem.go:154 +0xda
vervet-underground/internal/scraper_test.TestScraperCollation(0xc0001eeb60)
        /Users/gabrielenslein/go/src/github.com/snyk/vervet/vervet-underground/internal/scraper/scraper_test.go:209 +0x805
testing.tRunner(0xc0001eeb60, 0x14c22b8)
        /usr/local/opt/go/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /usr/local/opt/go/libexec/src/testing/testing.go:1306 +0x35a

```
Perhaps some assistance monday?

2021-12-11 00:34 UTC, cmars reviewed
We're getting there! Just a few minor locking issues that can be easily addressed.

2021-12-11 00:34 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +	}
Slightly more compact:

```suggestion
	for i, value := range uniqueVersions {
		s.collatedVersions[i] = value
	}
```

2021-12-11 00:34 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +		if revisions, ok := s.serviceVersionMappedRevisionSpecs[service][version.String()]; ok {
This will need to be protected by the mutex.
```suggestion
		s.mu.RLock()
		revisions, ok := s.serviceVersionMappedRevisionSpecs[service][version.String()]
		s.mu.RUnlock()
		if ok {
```

2021-12-11 00:34 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +		if revisions, ok := s.serviceVersionMappedRevisionSpecs[service][resolvedVersion.String()]; ok {
This will need a read lock as well.

2021-12-11 00:34 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +	s.collatedVersionedSpecs[version] = *dst
```suggestion
	s.mu.Lock()
	s.collatedVersionedSpecs[version] = *dst
	s.mu.Unlock()
```

2021-12-11 00:34 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +			log.Error().Err(err).Msgf("Could not Marshal Version %s", key.String())
Your call, but I usually let these kinds of errors bubble up to the top and log there.

2021-12-11 00:34 UTC, cmars commented on vervet-underground/internal/storage/mem/mem.go
> +			errs = multierr.Append(errs, err)
Minor suggestion, but might be more compact and less chatty to 

```suggestion
			errs = multierr.Append(errs, errors.Wrapf(err, "failed to collate version %s", version.String())
```

and let the caller log the error? `multierr` should show all of them when you log it.

2021-12-11 00:37 UTC, cmars commented
> Perhaps some assistance monday?

Absolutely!

2021-12-13 14:09 UTC, genslein commented on vervet-underground/internal/storage/mem/mem.go
> +	}
`uniqueVersions` is a map. The mechanism is to use the map for creating uniqueness in the array, and then inserting all the values and presizing the array.

I could simplify the code to just use `append` instead if you'd rather but this is slightly more memory efficient

2021-12-13 15:38 UTC, cmars approved these changes
LGTM with latest revision of a version in collated versions.

2021-12-13 16:56 UTC, merged