Feat/present compiled vu
snyk/vervet pull request #96
Opened 2021-12-13 19:10 UTC by genslein

Initial draft exposing data via the web API 

Will be writing specs shortly

2021-12-13 19:20 UTC, cmars reviewed
Off to a great start here. Only thing I think is missing is a background goroutine that operates the scraper. We probably also want to scrape on first startup before we start serving, so we don't panic (in the anxiety sense) our clients with an empty list of spec versions.

2021-12-13 19:20 UTC, cmars commented on vervet-underground/internal/scraper/scraper.go
> +	Versions() []string
Storage can likely fail any operation when we consider implementations other than `mem`. I'm fine with leaving that as a followup refactor though; internal packages give us that freedom.

2021-12-13 19:20 UTC, cmars commented on vervet-underground/server.go
> +		panic("unable to load storage")
Something to consider here is, introducing an `App` or `Service` that does all the setup and starts/stops everything (like a supervisor, basically), returning the error early here. Then `main` can panic once on setup error, in one place. Also might be useful to run in an integration test harness.

2021-12-13 19:21 UTC, genslein commented on vervet-underground/server.go
> +		panic("unable to load storage")
Yeah, I was going to start pulling things out to do setups. This was the first scaffold but early view here

2021-12-13 20:26 UTC, genslein commented on vervet-underground/internal/scraper/scraper.go
> +	Versions() []string
Yeah, probably once we get to additional features this interface will change

2021-12-14 00:31 UTC, cmars requested changes
Please don't remove `context` from the scraper. Explanations below. Happy to discuss further.

2021-12-14 00:31 UTC, cmars commented on vervet-underground/internal/scraper/scraper.go
> +func (s *Scraper) Run() error {
Disagree with removing the context. `context.WithTimeout` or `context.WithCancel` would be the preferred way to cancel a scrape in progress (and already worked).

See https://pkg.go.dev/context#section-documentation for background on how context is typically used.

2021-12-14 00:31 UTC, cmars commented on vervet-underground/internal/scraper/scraper_test.go
> +	_, cancel := context.WithTimeout(context.Background(), time.Second*10)
This no longer does anything. Setting a timeout on the context ensured the scraper would shut down after 10s, so we don't potentially hang the test.

2021-12-14 00:31 UTC, cmars commented on vervet-underground/internal/scraper/scraper.go
> +		http:    &http.Client{Timeout: timeout},
A [scraper.HTTPClient](https://github.com/snyk/vervet/blob/cc8fe6323cb19a6905c6cffd3b1a1f36412db26b/vervet-underground/internal/scraper/scraper.go#L83) option can already be passed to `scraper.New`. That would allow configuration of the client timeout. And the context we were using should have already handled cleaning up all active client connections in progress and goroutines when it is canceled or times out.

2021-12-14 00:31 UTC, cmars commented on vervet-underground/internal/scraper/scraper.go
> -	req, err := http.NewRequestWithContext(ctx, "GET", svc.url.String(), nil)
See https://pkg.go.dev/net/http#NewRequestWithContext, "the context controls the entire lifetime of a request and its response"

2021-12-14 13:49 UTC, genslein commented on vervet-underground/internal/scraper/scraper.go
> -	req, err := http.NewRequestWithContext(ctx, "GET", svc.url.String(), nil)
https://pkg.go.dev/net/http#NewRequest wraps under the hood `context.Background()` and calls `NewRequestWithContext`. We don't need to handle things this way.

2021-12-14 16:14 UTC, cmars commented on vervet-underground/internal/scraper/scraper.go
> -	req, err := http.NewRequestWithContext(ctx, "GET", svc.url.String(), nil)
So the idea with passing in a context is that a cancel or timeout at a level above will cascade down to all the scraper goroutines and their clients. This allows you to shut down the service at the top level by canceling a "root" context, which will cascade down to all its children and immediately abort all requests in progress. Or, you could run a scrape with a timeout; run a scrape for up to 15 minutes, then alert and give up. You might need to detect a hang not only due to the service scrapes (which can be mitigated with a client timeout) but also storage issues.

2021-12-14 16:41 UTC, genslein commented on vervet-underground/internal/scraper/scraper.go
> -	req, err := http.NewRequestWithContext(ctx, "GET", svc.url.String(), nil)
Then `graceful-timeout` is far too small and should be done per run. Also we don't actually check `Done()` further down (see https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/net/http/server.go;l=2734-2744)  So while I agree we need some context, this is setting a per http request timeout. 

We'd want a separate timeout from the initial one set from the top-level `Run` which is not really set up right now.

2021-12-14 16:41 UTC, genslein commented on vervet-underground/internal/scraper/scraper.go
> +		http:    &http.Client{Timeout: timeout},
refactored

2021-12-14 16:43 UTC, genslein commented on vervet-underground/internal/scraper/scraper.go
> -	req, err := http.NewRequestWithContext(ctx, "GET", svc.url.String(), nil)
Let's chat about options here but the initial context object needs to be branched correctly downstream and the max timeout needs to be significantly larger

2021-12-14 19:33 UTC, genslein commented on vervet-underground/internal/scraper/scraper.go
> -	req, err := http.NewRequestWithContext(ctx, "GET", svc.url.String(), nil)
Will defer hardening `Context` layers after landing.

2021-12-15 13:54 UTC, merged

2021-12-16 23:08 UTC, snyksec commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@snyk/vervet/v/1.4.0)
- [GitHub release](https://github.com/snyk/vervet/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: